spring.application.name=bdget-consumer

logging.level.root=INFO
logging.level.org.hibernate=INFO
logging.level.org.springframework=INFO

# ----------------------------
# BASE DE DATOS ORACLE
# ----------------------------
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ----------------------------
# JPA / HIBERNATE
# ----------------------------
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# ----------------------------
# HIKARI
# ----------------------------
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

# ----------------------------
# PUERTO
# ----------------------------
server.port=8081

# ----------------------------
# RABBITMQ
# ----------------------------
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:admin}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:admin123}

# ----------------------------
# AWS
# ----------------------------

cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:}
cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:}
cloud.aws.credentials.session-token=${AWS_SESSION_TOKEN:}
cloud.aws.region.static=${AWS_REGION:us-east-1}
cloud.aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:}

storage.efs.base-path=${EFS_BASE_PATH:/app/efs}

spring.autoconfigure.exclude=io.awspring.cloud.autoconfigure.s3.S3AutoConfiguration